### ISSUE TITLE
Character responds to an earlier d-pad input after battle.

### ISSUE THREAD

**Issue by ghost** [fellowship-of-the-roms/pokecrystal#4]
Character facing to a different direction after battle if you do rapid movement to get an encounter.

![flip](https://github.com/fellowship-of-the-roms/pokecrystal/assets/89683057/6be9e0bd-a052-4e27-a6c3-e21a5f3000c3)

**Branch:** Unmodified [Doublespeed-60fps-Running-Shoes](https://github.com/fellowship-of-the-roms/pokecrystal/tree/Doublespeed-60fps-Running-Shoes)

**Comment by vulcandth** [comment]
Forgot to actually apply the commit... standby.

**Comment by vulcandth** [comment]
Resolved in e27a0d2e5c6fbd2fdd29eb8202938c9dcbad0f8e
