### ISSUE TITLE
Mt. Moon Square Clefairy movement issues

### ISSUE THREAD

**Issue by ghost** [fellowship-of-the-roms/pokecrystal#5]
![moon](https://github.com/fellowship-of-the-roms/pokecrystal/assets/89683057/22bba38c-069b-45ef-b666-286acee134dd)

**Branch:** Unmodified [Doublespeed-60fps-Running-Shoes](https://github.com/fellowship-of-the-roms/pokecrystal/tree/Doublespeed-60fps-Running-Shoes)

**Comment by vulcandth** [comment]
Thanks I'll take a look soon!

**Comment by vulcandth** [comment]
(Forgot to actually apply the commit.. standby..

**Comment by vulcandth** [comment]
Resolved in e197ef4b501077c4501f5ede69b35e1b4a67913d
